window.EXAM = {
  lectures: [
    {id:"lec01",title:"授業概要・生成AI使用上の注意事項",pages:12},
    {id:"lec02",title:"生成AIを使う②・プロンプトエンジニアリング・生成AIの仕組み①",pages:27},
    {id:"lec03",title:"生成AIの仕組み②：Transformer・Attention・埋め込みベクトル・深層学習",pages:37},
    {id:"lec04",title:"脳のモデル・ニューラルネットワーク・学習アルゴリズム",pages:21},
    {id:"lec05",title:"AIの歴史・古典的知識表現",pages:22},
    {id:"lec06",title:"推論とアブダクション",pages:19},
    {id:"lec08",title:"未来のAI：フィジカルAI・エージェント・人とAIの共生",pages:30}
  ],

  glossary: [
    {term:"ハルシネーション",reading:"はるしねーしょん",definition:"人工知能によって生成された、虚偽または誤解を招く情報を事実かのように提示する応答のこと。内因性（学習データと異なる出力）と外因性（学習データに存在しないことを出力）に分かれる。",lecture_id:"lec01",page:9},
    {term:"内因性ハルシネーション",reading:"",definition:"学習データと異なる出力をするハルシネーション。",lecture_id:"lec01",page:9},
    {term:"外因性ハルシネーション",reading:"",definition:"学習データに存在しないことを出力するハルシネーション。",lecture_id:"lec01",page:9},
    {term:"権利侵害",reading:"",definition:"AIが学習したデータに他者が権利を有するコンテンツが含まれており、そのAIが生成した結果を使用すると著作権・肖像権などの侵害につながる恐れがあること。",lecture_id:"lec01",page:10},
    {term:"情報漏洩",reading:"",definition:"使用する生成AIによっては、ユーザが入力した情報がAIの改善学習に使われる場合があり、個人情報や機密情報が漏洩するリスクがあること。",lecture_id:"lec01",page:11},
    {term:"バイアス（偏り）",reading:"",definition:"生成AIの出力結果に生じる偏り。特定の集団や観点に偏った応答が生成されることがある。",lecture_id:"lec01",page:12},
    {term:"ブラックボックス",reading:"",definition:"生成AIの回答生成過程が不透明で、根拠が分からない性質のこと。",lecture_id:"lec01",page:12},
    {term:"ディープフェイク",reading:"",definition:"AIを用いて人物の顔や音声などを偽造・合成した偽の映像・音声コンテンツ。",lecture_id:"lec01",page:12},
    {term:"ファクトチェック",reading:"",definition:"生成AIの出力結果が正しいかどうかを自身でウェブ等を検索して確認すること。AIの出力を無批判に信用しないために必須の行為。",lecture_id:"lec01",page:9},
    {term:"オプトアウト",reading:"",definition:"自身の入力データが学習に使われることを拒否する設定オプション。",lecture_id:"lec01",page:11},
    {term:"DeepResearch（DeepSearch）",reading:"",definition:"ユーザがウェブを行き来しながら行っていた調査プロセスをAIエージェントが代行し、レポートにまとめてくれる生成AIサービスの機能。",lecture_id:"lec02",page:3},
    {term:"AIエージェント",reading:"",definition:"ワークフローを設計し、利用可能なツールを活用することで、ユーザまたは別のシステムに代わってタスクを自律的に実行できるシステムまたはプログラム。",lecture_id:"lec02",page:3},
    {term:"プロンプトエンジニアリング",reading:"",definition:"AIのモデルから所望の出力を得るためのプロンプトを作成するプロセス。モデルに正確な指示・例・必要な文脈情報を与えることで出力を改善できる。",lecture_id:"lec02",page:8},
    {term:"コンテキストエンジニアリング",reading:"",definition:"LLMへの指示よりも、LLMの推論過程を助けうる様々な情報（コンテキスト）を与えることに注目するアプローチ。RAGや短期/長期記憶が代表例。",lecture_id:"lec02",page:16},
    {term:"RAG（Retrieval-Augmented Generation）",reading:"",definition:"外部データベースをLLMの推論過程に統合活用するコンテキストエンジニアリングの代表例。",lecture_id:"lec02",page:16},
    {term:"システムプロンプト",reading:"",definition:"役割・目的・ルール・出力形式といった情報を予め与えることで、LLMの振る舞いを制御するプロンプト。",lecture_id:"lec02",page:16},
    {term:"Chain of Thought（思考の連鎖）",reading:"",definition:"タスクを完了するための必要ステップを明示的にモデルに示すプロンプト手法。複雑な問題を段階的に処理させることができる。",lecture_id:"lec02",page:13},
    {term:"Few-shot prompting",reading:"",definition:"モデルに例を提供することで、期待する出力形式や解法のパターンを示すプロンプト手法。",lecture_id:"lec02",page:14},
    {term:"GPT（Generative Pre-trained Transformer）",reading:"",definition:"OpenAIが開発した言語モデル。生成（Generative）・事前学習済み（Pre-trained）・トランスフォーマー（Transformer）の頭文字。",lecture_id:"lec02",page:20},
    {term:"LLM（Large Language Model）",reading:"",definition:"大規模言語モデル。基本処理は「トークンを入力して、続くトークンを出力する」こと。大規模テキストデータで事前学習後にファインチューニングされる。",lecture_id:"lec02",page:24},
    {term:"創発的能力",reading:"",definition:"近年のLLMが、直接教えていないタスクにも対応できる能力。大量のテキストデータを学習することで獲得される汎用性の高い能力。",lecture_id:"lec02",page:27},
    {term:"ファインチューニング",reading:"",definition:"事前学習済みLLMをさらに特定のタスク用データで追加学習する工程。対話型LLMは対話データでファインチューニングすることで得られる。",lecture_id:"lec02",page:26},
    {term:"自己回帰言語モデル",reading:"",definition:"前の出力を次の入力に使いながら逐次的にトークンを予測していく言語モデル。",lecture_id:"lec02",page:22},
    {term:"表現（representation）",reading:"ひょうげん",definition:"概念をプログラムでどう表現するかというAIの根本問題。古典AIは変数（記号）で表現し、現代AIは高次元ベクトルで表現する。",lecture_id:"lec03",page:4},
    {term:"高次元ベクトル表現",reading:"",definition:"概念を高次元の数値ベクトルとして表現する方式。類似した概念ほど似たベクトルになり、概念間の関係性も表現できる。",lecture_id:"lec03",page:5},
    {term:"埋め込みベクトル（embedding）",reading:"うめこみべくとる",definition:"高次元ベクトルに様々な意味を埋め込んだ表現。TransformerやAttentionの基本原理の一つ。GPT-3では12288次元のベクトル表現が用いられた。",lecture_id:"lec03",page:7},
    {term:"Transformer",reading:"",definition:"多くの生成AIの基盤をなす深層ニューラルネットワークモデル。2017年に発表。元々テキスト翻訳用に開発され、再帰や畳み込みを行わず並列化しやすい。",lecture_id:"lec03",page:9},
    {term:"トークン",reading:"とーくん",definition:"テキストデータを細かく分割した時の一つひとつの単位。それぞれのトークンには一意の数字（トークンID）が割り当てられる。",lecture_id:"lec03",page:12},
    {term:"トークナイザ",reading:"とーくないざ",definition:"テキストをトークンID列に変換する処理（エンコード）と、トークンID列をテキストに変換する処理（デコード）を担うモジュール。",lecture_id:"lec03",page:11},
    {term:"BPE（Byte Pair Encoding）",reading:"",definition:"頻繁に出現するサブワードのペアを順次マージして語彙数を減らすアルゴリズム。この語彙表を用いてエンコード/デコードを行う。",lecture_id:"lec03",page:14},
    {term:"注意機構（Attention）",reading:"ちゅういきこう",definition:"トークン間の関連性を扱えるようにする仕組み。Q・K・Vという3つの行列を用いて、距離的に遠い関係性も扱える。",lecture_id:"lec03",page:24},
    {term:"クエリ行列Q・キー行列K・バリュー行列V",reading:"",definition:"Attentionの中核データ構造。QをもとにKを検索し、結果をもとにVを取得する。役割はデータから自動的に学習される。",lecture_id:"lec03",page:25},
    {term:"マスク付きマルチヘッド注意機構",reading:"",definition:"未来の情報を参照しないようマスク処理を加えた、複数並列のAttention機構。Transformerのデコーダ版に用いられる。",lecture_id:"lec03",page:23},
    {term:"誤差逆伝搬法（Backpropagation）",reading:"",definition:"順伝搬計算で各層の値を求めた後、逆伝搬計算で勾配ベクトルを効率的に求める手法。多層NNの学習を実現する根幹アルゴリズム。",lecture_id:"lec03",page:35},
    {term:"ドロップアウト",reading:"",definition:"学習時にランダムにニューロンを無効化することで過学習を防ぐ正則化手法。",lecture_id:"lec03",page:35},
    {term:"レイヤ正規化",reading:"",definition:"勾配消失や勾配爆発を防ぎ学習効率を上げるための正規化手法。深層学習において重要な工夫の一つ。",lecture_id:"lec03",page:35},
    {term:"表現学習（representation learning）",reading:"",definition:"知識や特徴量を人手を介さずデータから自動的に得られるようにする学習。高次元ベクトルや深層NNという「表現」方式と、大規模データ・GPU等のハードウェアによって実現された。",lecture_id:"lec03",page:37},
    {term:"ViT（Vision Transformer）",reading:"",definition:"画像に対してTransformerのAttention機構を適用したモデル。Attentionはテキストのみならず画像や音声にも適用可能である例。",lecture_id:"lec03",page:29},
    {term:"神経細胞（ニューロン）",reading:"しんけいさいぼう",definition:"ヒトの脳内に数百億〜1000億個存在する情報伝達の基本単位。細胞体・樹状突起・軸索に大別され、シナプスを介して他の細胞と接続し活動電位を発生させて情報を伝達する。",lecture_id:"lec04",page:4},
    {term:"シナプス",reading:"しなぷす",definition:"神経細胞同士の接続部位。脳内には約14兆個存在するとされ、全宇宙の銀河よりも多いと言われる。",lecture_id:"lec04",page:4},
    {term:"人工ニューロン",reading:"",definition:"McCullochとPittsが1943年に提案した、ニューロンおよびそのネットワークの数学的モデル。ヘヴィサイドの階段関数を使い0/1のみの入出力をとる。",lecture_id:"lec04",page:5},
    {term:"パーセプトロン",reading:"ぱーせぷとろん",definition:"Rosenblattが1958年に発表した視覚・脳機能の計算論的モデル。パターン認識（線形分離）を行う。S層・A層・R層から成る。",lecture_id:"lec04",page:6},
    {term:"ネオコグニトロン",reading:"ねおこぐにとろん",definition:"福島邦彦が1979年に発表した階層的多層神経回路。変形に強い視覚パターン認識能力を持ち、畳み込みニューラルネットワークの先駆け。",lecture_id:"lec04",page:8},
    {term:"教師あり学習",reading:"",definition:"学習させたい入出力関係のデータ（教師データ）を用いてNNを学習させる手法。損失関数を小さくするようにパラメータを更新していく。",lecture_id:"lec04",page:11},
    {term:"損失関数",reading:"そんしつかんすう",definition:"ニューラルネットワークの出力と教師データとの間の誤差から定義される関数。この値を小さくするようにパラメータを更新する。",lecture_id:"lec04",page:11},
    {term:"勾配降下法（Gradient Descent）",reading:"こうばいこうかほう",definition:"損失関数の勾配を計算し、その勾配に従って重みパラメータを更新していく学習手法。損失が小さくなる方向にパラメータを少しずつ動かす。",lecture_id:"lec04",page:12},
    {term:"確率的勾配降下法（SGD）",reading:"",definition:"全データではなくランダムなミニバッチに対して勾配を計算してパラメータを更新する手法。計算コストを削減しながら学習できる。",lecture_id:"lec04",page:15},
    {term:"AlexNet",reading:"",definition:"Krizhevsky等が2012年のILSVRC（ImageNet大規模画像認識コンペ）で優勝したCNN。深層学習ブームの火付け役となった。",lecture_id:"lec04",page:17},
    {term:"グリア細胞",reading:"",definition:"ヒトの脳内に神経細胞よりも圧倒的に多数存在する細胞。髄鞘の構成・各種物質の運搬を担うが全貌は未解明。現在の人工NNでは完全に無視されている。",lecture_id:"lec04",page:19},
    {term:"ダートマス会議（1956年）",reading:"だーとますかいぎ",definition:"J.McCarthyらが発起人となった会議で、この研究分野が「Artificial Intelligence（人工知能）」と呼ばれるようになったきっかけ。",lecture_id:"lec05",page:4},
    {term:"フレーム問題",reading:"ふれーむもんだい",definition:"McCarthyとHayesが1969年に指摘した問題。行動後に変化しなかった事柄を全て記述・管理することの困難さ。古典的AIの根本的な限界を示す。",lecture_id:"lec05",page:10},
    {term:"エキスパートシステム",reading:"えきすぱーとしすてむ",definition:"人間の専門家のように知識と推論によって問題解決をはかるシステム。知識ベースと推論エンジンから成るルールベース（if…then…）システム。1980年代に商業的成功を収めたが限界に達した。",lecture_id:"lec05",page:11},
    {term:"論理表現",reading:"",definition:"物事に関する記述を真と偽に対応づけ、論理記述を組み合わせて新しい定理を導き出す知識表現。命題論理・一階述語論理が代表。",lecture_id:"lec05",page:17},
    {term:"プロダクションルール",reading:"",definition:"IF（条件）THEN（結論/行動）というルールの集合。連続的に適用して問題解決を行う。",lecture_id:"lec05",page:18},
    {term:"意味ネットワーク",reading:"",definition:"is-aリンク（性質の継承）とhas-aリンク（包含関係）を用いてノード（概念）間の関係をネットワーク構造で表現する知識表現方式。",lecture_id:"lec05",page:19},
    {term:"フレーム表現",reading:"",definition:"Minskyにより提唱された知識表現。インスタンスフレームとクラスフレームから構成。デフォルト値と性質の継承が重要概念。オブジェクト指向の礎。",lecture_id:"lec05",page:20},
    {term:"デフォルト値",reading:"",definition:"フレーム表現において、確定値は不明だが推定値はわかっている場合に仮に与える値。例：人の身長はdefault 170cm。",lecture_id:"lec05",page:22},
    {term:"性質の継承（inheritance）",reading:"",definition:"集合と要素・上位概念と下位概念等の関係がある時、上位→下位へと性質を伝える仕組み。意味ネットワーク・フレーム表現の両方で重要。",lecture_id:"lec05",page:22},
    {term:"演繹（deduction）",reading:"えんえき",definition:"前提とその結論との間に必然性の論理的関係がある分析的推論。三段論法が代表例。前提の内容を超えた知識の拡張はない。",lecture_id:"lec06",page:7},
    {term:"帰納（induction）",reading:"きのう",definition:"前提の内容を超えて新しい知識や情報を与える拡張的推論。前提が真でも結論が偽になりえる（蓋然的推論）。個々の事例から一般的な規則を導く。",lecture_id:"lec06",page:10},
    {term:"アブダクション（abduction）",reading:"あぶだくしょん",definition:"驚くべき事実Cを観察し、「もしHが真であればCは当然の事柄であろう」という仮説Hを構成する拡張的推論。仮説の発見を含む点が帰納と異なる。",lecture_id:"lec06",page:12},
    {term:"驚くべき事実C",reading:"",definition:"アブダクションの起点となる、既存の知識では説明できない観察事実。ニュートンの例では「林檎が垂直に落下する」こと。",lecture_id:"lec06",page:12},
    {term:"説明仮説H",reading:"",definition:"アブダクションにおいて、驚くべき事実Cを説明するために構成される仮説。ニュートンの例では「万有引力の法則」。",lecture_id:"lec06",page:12},
    {term:"蓋然的推論",reading:"がいぜんてきすいろん",definition:"前提が真であっても結論が偽になる可能性がある推論。帰納とアブダクションはともに蓋然的推論に属する。",lecture_id:"lec06",page:10},
    {term:"記号接地問題",reading:"きごうせっちもんだい",definition:"中国語辞書（中中辞典）のみから中国語の意味を理解できるかという問い。記号から記号へと回り続けるメリーゴーランドのような状態を指す。Harnad(1990)が提起。",lecture_id:"lec06",page:19},
    {term:"三段論法",reading:"",definition:"「すべてのAはBである・CはAである・ゆえにCはBである」という演繹推論の基本形式。",lecture_id:"lec06",page:7},
    {term:"フィジカルAI",reading:"",definition:"身体を持って実世界で動くAI。ロボット・ヒューマノイド・自動運転車などが含まれる。触覚・力覚などのデータが少なく実世界データの取得と学習が課題。",lecture_id:"lec08",page:4},
    {term:"デジタルツイン",reading:"",definition:"現実世界のデジタルコピーを仮想世界に再現し、その上でシミュレーション・機械学習を行い、得られた知見を現実世界にフィードバックして活用する技術。",lecture_id:"lec08",page:7},
    {term:"Sim2Real",reading:"",definition:"シミュレーション（仮想環境）で学習したポリシーや知識を実ロボットに適用する技術。",lecture_id:"lec08",page:9},
    {term:"VLA（Vision-Language-Action）モデル",reading:"",definition:"カメラ画像（V）と言語指示（L）をもとにロボットの行動（A）を出力するモデル。",lecture_id:"lec08",page:13},
    {term:"アフォーダンス",reading:"あふぉーだんす",definition:"物体が持つ、それを使う主体に対して提供する行動可能性。ロボットが新しい機器の使い方を汎化して学習するためのポイントとして研究されている。",lecture_id:"lec08",page:12},
    {term:"エージェンシー認知",reading:"えーじぇんしーにんち",definition:"環境内のある事物の振る舞いに対して、それが自律的な目的あるいは志向性に基づくものであると認知される心理的反応。「心を持っているようだ」という認識を与える。",lecture_id:"lec08",page:18},
    {term:"AIアラインメント",reading:"",definition:"AIと人間の価値観・目標を整合させること。人とAIがどう共生していくかという大きな課題への具体的アプローチ。",lecture_id:"lec08",page:22},
    {term:"Agentic Family System（AFS）",reading:"",definition:"田中研が開発中の、人とAIから構成される「家族」を最小単位の共生社会と捉えたシステム基盤。Olsonの円環モデル等を人-AI家族に拡張する。",lecture_id:"lec08",page:24}
  ],

  questions: {
    fill_blank: [
      // lec01
      {id:"fb001",lecture_id:"lec01",page:9,mode:"choice",
        text:"AIが虚偽または誤解を招く情報を事実かのように提示する応答を____という。", texts:["AIが虚偽または誤解を招く情報を事実かのように提示する応答を____という。", "____とは、AIが虚偽または誤解を招く情報を事実かのように提示する応答のことである。"],
        answer:"ハルシネーション",choices:["ハルシネーション","ファクトチェック","ブラックボックス","バイアス"],
        accept:["ハルシネーション","hallucination"],
        explanation:"ウィキペディアの定義では「人工知能によって生成された、虚偽または誤解を招く情報を事実かのように提示する応答」。"},
      {id:"fb002",lecture_id:"lec01",page:9,mode:"choice",
        text:"学習データに存在しないことを出力するハルシネーションを____ハルシネーションという。", texts:["学習データに存在しないことを出力するハルシネーションを____ハルシネーションという。", "学習データに存在しないことを出力するハルシネーションを____ハルシネーションという。"],
        answer:"外因性",choices:["外因性","内因性","論理的","統計的"],
        accept:["外因性"],
        explanation:"ハルシネーションは①学習データと異なる出力をする「内因性」と、②学習データに存在しないことを出力する「外因性」に分かれる。"},
      {id:"fb003",lecture_id:"lec01",page:11,mode:"choice",
        text:"自身の入力データが学習に使われることを拒否する設定オプションを____という。", texts:["自身の入力データが学習に使われることを拒否する設定オプションを____という。", "____とは、自身の入力データが学習に使われることを拒否する設定オプションのことである。"],
        answer:"オプトアウト",choices:["オプトアウト","オプトイン","ファインチューニング","プロンプト"],
        accept:["オプトアウト","opt-out"],
        explanation:"無料版のAIサービスでもオプトアウト設定などがある場合があるが、要注意情報は入力しないほうが安全。"},
      {id:"fb004",lecture_id:"lec01",page:12,mode:"input",
        text:"生成AIの回答生成過程が不透明で根拠が分からない性質を____という。", texts:["生成AIの回答生成過程が不透明で根拠が分からない性質を____という。", "____とは、生成AIの回答生成過程が不透明で根拠が分からない性質のことである。"],
        answer:"ブラックボックス",accept:["ブラックボックス","black box","blackbox"],
        explanation:"ブラックボックス問題は生成AIの「根拠が分からない」という特性を指す。説明可能AI（XAI）がこの問題に取り組んでいる。"},
      {id:"fb005",lecture_id:"lec01",page:9,mode:"input",
        text:"生成AIの出力が正しいかどうかを自身でウェブ等で確認することを____という。", texts:["生成AIの出力が正しいかどうかを自身でウェブ等で確認することを____という。", "____とは、生成AIの出力が正しいかどうかを自身でウェブ等で確認することのことである。"],
        answer:"ファクトチェック",accept:["ファクトチェック","ファクト チェック","fact check","factcheck"],
        explanation:"AIの出力を無批判に信用せず、ファクトチェックを忘れないことが重要。"},
      // lec02
      {id:"fb006",lecture_id:"lec02",page:20,mode:"choice",
        text:"GPTは Generative Pre-trained ____ の略である。", texts:["GPTは Generative Pre-trained ____ の略である。", "GPTは Generative Pre-trained ____ の略である。"],
        answer:"Transformer",choices:["Transformer","Tokenizer","Text-encoder","Trainer"],
        accept:["transformer","トランスフォーマー"],
        explanation:"GPT = Generative（生成）・Pre-trained（事前学習済み）・Transformer（トランスフォーマー）の略。"},
      {id:"fb007",lecture_id:"lec02",page:13,mode:"choice",
        text:"タスクを完了するための必要ステップを明示的にモデルに示すプロンプト手法を____という。", texts:["タスクを完了するための必要ステップを明示的にモデルに示すプロンプト手法を____という。", "____とは、タスクを完了するための必要ステップを明示的にモデルに示すプロンプト手法のことである。"],
        answer:"Chain of Thought（思考の連鎖）",choices:["Chain of Thought（思考の連鎖）","Few-shot prompting","RAG","システムプロンプト"],
        accept:["chain of thought","cot","思考の連鎖"],
        explanation:"CoT（Chain of Thought）は複雑な問題を段階的に処理させることができ、OpenAIの6戦略の「モデルに考える時間を与える」に対応する。"},
      {id:"fb008",lecture_id:"lec02",page:14,mode:"choice",
        text:"モデルに例を提供することで期待する出力形式や解法のパターンを示す手法を____という。", texts:["モデルに例を提供することで期待する出力形式や解法のパターンを示す手法を____という。", "____とは、モデルに例を提供することで期待する出力形式や解法のパターンを示す手法のことである。"],
        answer:"Few-shot prompting",choices:["Few-shot prompting","Zero-shot","Chain of Thought","RAG"],
        accept:["few-shot","few shot","few-shot prompting","フューショット"],
        explanation:"Few-shot promptingは現在でも非常に有効なプロンプト手法。0例の場合はZero-shot。"},
      {id:"fb009",lecture_id:"lec02",page:16,mode:"choice",
        text:"外部データベースをLLMの推論過程に統合活用するコンテキストエンジニアリングの代表例を____という。", texts:["外部データベースをLLMの推論過程に統合活用するコンテキストエンジニアリングの代表例を____という。", "____とは、外部データベースをLLMの推論過程に統合活用するコンテキストエンジニアリングの代表例のことである。"],
        answer:"RAG",choices:["RAG","CoT","LoRA","SFT"],
        accept:["rag","retrieval-augmented generation","検索拡張生成"],
        explanation:"RAG（Retrieval-Augmented Generation）はLLMの知識不足や古い情報問題を補うためにも用いられる。"},
      {id:"fb010",lecture_id:"lec02",page:27,mode:"choice",
        text:"近年のLLMが、直接教えていないタスクにも対応できる能力を____という。", texts:["近年のLLMが、直接教えていないタスクにも対応できる能力を____という。", "____とは、近年のLLMが、直接教えていないタスクにも対応できる能力のことである。"],
        answer:"創発的能力",choices:["創発的能力","ファインチューニング","転移学習","メタ学習"],
        accept:["創発的能力","emergent ability","創発"],
        explanation:"創発的能力は従来の特化型AIにはなかった性質で、大量のテキストデータ学習によって獲得される。"},
      {id:"fb011",lecture_id:"lec02",page:24,mode:"input",
        text:"LLM（Large Language Model）の基本処理は「____を入力して、続く____を出力する」ことである。", texts:["LLM（Large Language Model）の基本処理は「____を入力して、続く____を出力する」ことである。", "LLM（Large Language Model）の基本処理は「____を入力して、続く____を出力する」ことである。"],
        answer:"トークン",accept:["トークン","token"],
        explanation:"LLMはトークンIDの列を入力として受け取り、続くトークンIDの確率分布を出力する。"},
      {id:"fb012",lecture_id:"lec02",page:26,mode:"choice",
        text:"事前学習済みLLMをさらに特定のタスク用データで追加学習する工程を____という。", texts:["事前学習済みLLMをさらに特定のタスク用データで追加学習する工程を____という。", "____とは、事前学習済みLLMをさらに特定のタスク用データで追加学習する工程のことである。"],
        answer:"ファインチューニング",choices:["ファインチューニング","プレトレーニング","RAG","プロンプトエンジニアリング"],
        accept:["ファインチューニング","fine-tuning","fine tuning","微調整"],
        explanation:"ChatGPTは対話データでファインチューニングした対話型LLMを使用している。"},
      // lec03
      {id:"fb013",lecture_id:"lec03",page:14,mode:"choice",
        text:"頻繁に出現するサブワードのペアを順次マージして語彙数を減らすアルゴリズムを____という。", texts:["頻繁に出現するサブワードのペアを順次マージして語彙数を減らすアルゴリズムを____という。", "____とは、頻繁に出現するサブワードのペアを順次マージして語彙数を減らすアルゴリズムのことである。"],
        answer:"BPE（Byte Pair Encoding）",choices:["BPE（Byte Pair Encoding）","WordPiece","SentencePiece","Unigram"],
        accept:["bpe","byte pair encoding","バイトペアエンコーディング"],
        explanation:"BPEはGPTシリーズで採用されているサブワードトークナイズ手法。頻出ペアを繰り返しマージして語彙表を作る。"},
      {id:"fb014",lecture_id:"lec03",page:25,mode:"choice",
        text:"Attentionでは____行列で____行列を検索し、結果をもとに____行列を取得する。", texts:["Attentionでは____行列で____行列を検索し、結果をもとに____行列を取得する。", "Attentionでは____行列で____行列を検索し、結果をもとに____行列を取得する。"],
        answer:"Q・K・V",choices:["Q・K・V","K・Q・V","V・K・Q","Q・V・K"],
        accept:["q k v","q・k・v","クエリ キー バリュー"],
        explanation:"Q（クエリ）でK（キー）を検索し、対応するV（バリュー）を取得するのがAttentionの基本動作。"},
      {id:"fb015",lecture_id:"lec03",page:9,mode:"input",
        text:"多くの生成AIの基盤をなす深層NNモデルは____であり、2017年に発表された。", texts:["多くの生成AIの基盤をなす深層NNモデルは____であり、2017年に発表された。", "多くの生成AIの基盤をなす深層NNモデルは____であり、____年に発表された。"],
        answer:"Transformer",accept:["transformer","トランスフォーマー"],
        explanation:"Transformerは2017年にVaswani et al.が発表。元々テキスト翻訳用に開発され、再帰や畳み込みを行わない。"},
      {id:"fb016",lecture_id:"lec03",page:21,mode:"choice",
        text:"「A dog bites a man.」と「A man bites a dog.」でdogやmanのテキスト埋め込みは同一だが位置が異なる。これを解決するのが____である。", texts:["「A dog bites a man.」と「A man bites a dog.」でdogやmanのテキスト埋め込みは同一だが位置が異なる。これを解決するのが____である。", "「A dog bites a man.」と「A man bites a dog.」でdogやmanのテキスト埋め込みは同一だが位置が異なる。これを解決するのが____である。"],
        answer:"位置埋め込み",choices:["位置埋め込み","テキスト埋め込み","語彙表","BPE"],
        accept:["位置埋め込み","positional encoding","位置エンコーディング"],
        explanation:"位置埋め込みは各トークンの入力文中における位置情報を付与する。これにより語順の違いを表現できる。"},
      {id:"fb017",lecture_id:"lec03",page:35,mode:"choice",
        text:"学習時にランダムにニューロンを無効化することで過学習を防ぐ手法を____という。", texts:["学習時にランダムにニューロンを無効化することで過学習を防ぐ手法を____という。", "____とは、学習時にランダムにニューロンを無効化することで過学習を防ぐ手法のことである。"],
        answer:"ドロップアウト",choices:["ドロップアウト","レイヤ正規化","L2正則化","早期終了"],
        accept:["ドロップアウト","dropout"],
        explanation:"ドロップアウトは過学習防止の正則化手法。学習時のみランダムにニューロンを無効化する。"},
      {id:"fb018",lecture_id:"lec03",page:35,mode:"choice",
        text:"勾配消失や勾配爆発を防ぎ学習効率を上げる正規化手法を____という。", texts:["勾配消失や勾配爆発を防ぎ学習効率を上げる正規化手法を____という。", "____とは、勾配消失や勾配爆発を防ぎ学習効率を上げる正規化手法のことである。"],
        answer:"レイヤ正規化",choices:["レイヤ正規化","ドロップアウト","バッチ正規化","重み正規化"],
        accept:["レイヤ正規化","layer normalization","layernorm"],
        explanation:"レイヤ正規化はTransformerにおいて深層学習を安定させる重要な工夫の一つ。"},
      {id:"fb019",lecture_id:"lec03",page:37,mode:"input",
        text:"知識や特徴量を人手を介さずデータから自動的に得られるようにする学習を____という。", texts:["知識や特徴量を人手を介さずデータから自動的に得られるようにする学習を____という。", "____とは、知識や特徴量を人手を介さずデータから自動的に得られるようにする学習のことである。"],
        answer:"表現学習",accept:["表現学習","representation learning"],
        explanation:"表現学習革命により、人手でのボトルネックが解消され現代AIの汎用性能が格段に向上した。"},
      {id:"fb020",lecture_id:"lec03",page:7,mode:"choice",
        text:"GPT-3では____次元のベクトル表現が用いられた。", texts:["GPT-3では____次元のベクトル表現が用いられた。", "GPT-3では____次元のベクトル表現が用いられた。"],
        answer:"12288",choices:["12288","768","4096","2048"],
        accept:["12288"],
        explanation:"GPT-3の埋め込みベクトルは12288次元。この高次元ベクトルに様々な意味が埋め込まれる。"},
      // lec04
      {id:"fb021",lecture_id:"lec04",page:5,mode:"choice",
        text:"人工ニューロンを1943年に提案したのは____と____である。", texts:["人工ニューロンを1943年に提案したのは____と____である。", "人工ニューロンを1943年に提案したのは____と____である。"],
        answer:"McCullochとPitts",choices:["McCullochとPitts","RosenblattとHinton","MinskとPapert","HintonとLeCun"],
        accept:["mcculloch","ぴっつ","mcculloch pitts"],
        explanation:"McCullochとPittsが1943年に提案した人工ニューロンは、ヘヴィサイドの階段関数を使い0/1のみの入出力をとる。"},
      {id:"fb022",lecture_id:"lec04",page:6,mode:"choice",
        text:"パーセプトロンを1958年に発表したのは____である。", texts:["パーセプトロンを1958年に発表したのは____である。", "パーセプトロンを1958年に発表したのに当てはまるのは____である。"],
        answer:"Rosenblatt",choices:["Rosenblatt","McCulloch","Minsky","Hinton"],
        accept:["rosenblatt","ローゼンブラット"],
        explanation:"Rosenblattのパーセプトロン（1958）はS層・A層・R層から成り、線形分離可能な問題を解ける。"},
      {id:"fb023",lecture_id:"lec04",page:8,mode:"choice",
        text:"畳み込みニューラルネットワークの先駆けとされる____を1979年に発表したのは____である。", texts:["畳み込みニューラルネットワークの先駆けとされる____を1979年に発表したのは____である。", "畳み込みニューラルネットワークの先駆けとされる____を1979年に発表したのに当てはまるのは____である。"],
        answer:"ネオコグニトロン・福島邦彦",choices:["ネオコグニトロン・福島邦彦","パーセプトロン・Rosenblatt","AlexNet・Hinton","LeNet・LeCun"],
        accept:["ネオコグニトロン","福島","fukushima","neocognitron"],
        explanation:"ネオコグニトロン（1979）は階層的多層神経回路で、変形に強い視覚パターン認識能力を持つ。"},
      {id:"fb024",lecture_id:"lec04",page:11,mode:"choice",
        text:"ニューラルネットワークの出力と教師データとの誤差から定義される関数を____という。", texts:["ニューラルネットワークの出力と教師データとの誤差から定義される関数を____という。", "____とは、ニューラルネットワークの出力と教師データとの誤差から定義される関数のことである。"],
        answer:"損失関数",choices:["損失関数","活性化関数","勾配関数","正則化項"],
        accept:["損失関数","loss function","コスト関数"],
        explanation:"教師あり学習では損失関数を小さくするようにパラメータを更新していく。"},
      {id:"fb025",lecture_id:"lec04",page:17,mode:"choice",
        text:"2012年のILSVRC（ImageNet大規模画像認識コンペ）で優勝し、深層学習ブームの火付け役となったCNNを____という。", texts:["2012年のILSVRC（ImageNet大規模画像認識コンペ）で優勝し、深層学習ブームの火付け役となったCNNを____という。", "____とは、2012年のILSVRC（ImageNet大規模画像認識コンペ）で優勝し、深層学習ブームの火付け役となったCNNのことである。"],
        answer:"AlexNet",choices:["AlexNet","LeNet","ResNet","VGGNet"],
        accept:["alexnet","アレックスネット"],
        explanation:"AlexNetはKrizhevsky等が開発し、深層学習革命のきっかけとなった。その後GPUを活用した深層学習が急速に普及した。"},
      {id:"fb026",lecture_id:"lec04",page:19,mode:"input",
        text:"ヒトの脳内に神経細胞よりも多数存在するが、現在の人工NNでは完全に無視されている細胞を____という。", texts:["ヒトの脳内に神経細胞よりも多数存在するが、現在の人工NNでは完全に無視されている細胞を____という。", "____とは、ヒトの脳内に神経細胞よりも多数存在するが、現在の人工NNでは完全に無視されている細胞のことである。"],
        answer:"グリア細胞",accept:["グリア細胞","グリア","glia","glial cell"],
        explanation:"グリア細胞は髄鞘の構成・各種物質の運搬を担うが全貌は未解明。人工NNの限界の一例として紹介される。"},
      {id:"fb027",lecture_id:"lec04",page:12,mode:"choice",
        text:"損失関数の勾配を計算し、その勾配に従って重みパラメータを更新する学習手法を____という。", texts:["損失関数の勾配を計算し、その勾配に従って重みパラメータを更新する学習手法を____という。", "____とは、損失関数の勾配を計算し、その勾配に従って重みパラメータを更新する学習手法のことである。"],
        answer:"勾配降下法",choices:["勾配降下法","確率的勾配降下法","誤差逆伝搬法","ニュートン法"],
        accept:["勾配降下法","gradient descent"],
        explanation:"勾配降下法で損失が小さくなる方向にパラメータを少しずつ更新する。確率的勾配降下法（SGD）はそのミニバッチ版。"},
      // lec05
      {id:"fb028",lecture_id:"lec05",page:4,mode:"choice",
        text:"1956年に「Artificial Intelligence（人工知能）」という名称が生まれたきっかけとなった会議を____という。", texts:["1956年に「Artificial Intelligence（人工知能）」という名称が生まれたきっかけとなった会議を____という。", "____とは、1956年に「Artificial Intelligence（人工知能）」という名称が生まれたきっかけとなった会議のことである。"],
        answer:"ダートマス会議",choices:["ダートマス会議","チューリング会議","マッカーシー会議","MITシンポジウム"],
        accept:["ダートマス会議","ダートマス","dartmouth conference"],
        explanation:"J.McCarthyらが発起人となったダートマス会議（1956）で、この研究分野が「Artificial Intelligence」と呼ばれるようになった。"},
      {id:"fb029",lecture_id:"lec05",page:10,mode:"choice",
        text:"行動後に変化しなかった事柄を全て記述・管理することの困難さを指す問題を____という。", texts:["行動後に変化しなかった事柄を全て記述・管理することの困難さを指す問題を____という。", "____とは、行動後に変化しなかった事柄を全て記述・管理することの困難さを指す問題のことである。"],
        answer:"フレーム問題",choices:["フレーム問題","記号接地問題","停止問題","組合せ爆発"],
        accept:["フレーム問題","frame problem"],
        explanation:"フレーム問題はMcCarthyとHayesが1969年に指摘した古典的AIの根本的な限界。"},
      {id:"fb030",lecture_id:"lec05",page:11,mode:"choice",
        text:"知識ベースと推論エンジンから成るルールベースシステムを____という。", texts:["知識ベースと推論エンジンから成るルールベースシステムを____という。", "____とは、知識ベースと推論エンジンから成るルールベースシステムのことである。"],
        answer:"エキスパートシステム",choices:["エキスパートシステム","ニューラルネットワーク","ベイズ推論","意思決定木"],
        accept:["エキスパートシステム","expert system"],
        explanation:"エキスパートシステムは1980年代に商業的成功を収めたが、知識入力のコストや暗黙知の扱いで限界に達した。"},
      {id:"fb031",lecture_id:"lec05",page:19,mode:"choice",
        text:"意味ネットワークの____リンクは性質の継承を、____リンクは包含関係を表す。", texts:["意味ネットワークの____リンクは性質の継承を、____リンクは包含関係を表す。", "意味ネットワークの____リンクは性質の継承を、____リンクは包含関係を表す。"],
        answer:"is-a / has-a",choices:["is-a / has-a","has-a / is-a","type-of / part-of","kind-of / member-of"],
        accept:["is-a","isa","is a"],
        explanation:"is-aリンクは「カラスは鳥である」という継承関係、has-aリンクは「鳥は羽を持つ」という包含関係を表す。"},
      {id:"fb032",lecture_id:"lec05",page:20,mode:"choice",
        text:"フレーム表現を提唱したのは____である。", texts:["フレーム表現を提唱したのは____である。", "フレーム表現を提唱したのに当てはまるのは____である。"],
        answer:"Minsky",choices:["Minsky","McCarthy","Rosenblatt","Hinton"],
        accept:["minsky","ミンスキー"],
        explanation:"Minskyのフレーム表現はインスタンスフレームとクラスフレームから構成され、オブジェクト指向の礎となった。"},
      {id:"fb033",lecture_id:"lec05",page:22,mode:"choice",
        text:"フレーム表現において、確定値は不明だが推定値はわかっている場合に仮に与える値を____という。", texts:["フレーム表現において、確定値は不明だが推定値はわかっている場合に仮に与える値を____という。", "____とは、フレーム表現において、確定値は不明だが推定値はわかっている場合に仮に与える値のことである。"],
        answer:"デフォルト値",choices:["デフォルト値","インスタンス値","継承値","推論値"],
        accept:["デフォルト値","default","デフォルト"],
        explanation:"例：人の身長はdefault 170cm。必ずしも正しいとは限らないが、情報がない場合の推定に使う。"},
      {id:"fb034",lecture_id:"lec05",page:17,mode:"input",
        text:"IF（条件）THEN（結論/行動）というルールの集合を用いた知識表現を____という。", texts:["IF（条件）THEN（結論/行動）というルールの集合を用いた知識表現を____という。", "____とは、IF（条件）THEN（結論/行動）というルールの集合を用いた知識表現のことである。"],
        answer:"プロダクションルール",accept:["プロダクションルール","production rule","プロダクション"],
        explanation:"プロダクションルールは連続的に適用して問題解決を行う。エキスパートシステムの核心的手法の一つ。"},
      // lec06
      {id:"fb035",lecture_id:"lec06",page:7,mode:"choice",
        text:"前提とその結論との間に必然性の論理的関係がある分析的推論を____という。", texts:["前提とその結論との間に必然性の論理的関係がある分析的推論を____という。", "____とは、前提とその結論との間に必然性の論理的関係がある分析的推論のことである。"],
        answer:"演繹",choices:["演繹","帰納","アブダクション","類推"],
        accept:["演繹","deduction","えんえき"],
        explanation:"演繹は前提の内容を超えた知識の拡張はなく、前提に暗々裏に含まれる情報を解明する。三段論法が代表例。"},
      {id:"fb036",lecture_id:"lec06",page:10,mode:"choice",
        text:"個々の事例から一般的な規則を導く、前提を超えた知識拡張を持つ推論を____という。", texts:["個々の事例から一般的な規則を導く、前提を超えた知識拡張を持つ推論を____という。", "____とは、個々の事例から一般的な規則を導く、前提を超えた知識拡張を持つ推論のことである。"],
        answer:"帰納",choices:["帰納","演繹","アブダクション","三段論法"],
        accept:["帰納","induction","きのう"],
        explanation:"帰納は拡張的推論であり、前提が真でも結論が偽になりえる蓋然的推論に属する。"},
      {id:"fb037",lecture_id:"lec06",page:12,mode:"choice",
        text:"驚くべき事実Cを観察し、「もしHが真であればCは当然の事柄であろう」という仮説Hを構成する推論を____という。", texts:["驚くべき事実Cを観察し、「もしHが真であればCは当然の事柄であろう」という仮説Hを構成する推論を____という。", "____とは、驚くべき事実Cを観察し、「もしHが真であればCは当然の事柄であろう」という仮説Hを構成する推論のことである。"],
        answer:"アブダクション",choices:["アブダクション","帰納","演繹","アナロジー"],
        accept:["アブダクション","abduction"],
        explanation:"アブダクションは仮説の発見を含む拡張的推論。ニュートンの万有引力発見の思索がその典型例。"},
      {id:"fb038",lecture_id:"lec06",page:12,mode:"input",
        text:"アブダクションの起点となる、既存の知識では説明できない観察事実を____という。", texts:["アブダクションの起点となる、既存の知識では説明できない観察事実を____という。", "____とは、アブダクションの起点となる、既存の知識では説明できない観察事実のことである。"],
        answer:"驚くべき事実C",accept:["驚くべき事実c","驚くべき事実","surprising fact"],
        explanation:"ニュートンの例では「林檎が垂直に落下する」が驚くべき事実Cに当たる。"},
      {id:"fb039",lecture_id:"lec06",page:10,mode:"choice",
        text:"前提が真であっても結論が偽になる可能性がある推論を____という。", texts:["前提が真であっても結論が偽になる可能性がある推論を____という。", "____とは、前提が真であっても結論が偽になる可能性がある推論のことである。"],
        answer:"蓋然的推論",choices:["蓋然的推論","必然的推論","分析的推論","論理的推論"],
        accept:["蓋然的推論","がいぜんてきすいろん","probabilistic"],
        explanation:"帰納とアブダクションはともに蓋然的推論に属する。演繹は必然的推論。"},
      {id:"fb040",lecture_id:"lec06",page:19,mode:"choice",
        text:"中国語辞書（中中辞典）のみから中国語の意味を理解できるかという問いを____という。", texts:["中国語辞書（中中辞典）のみから中国語の意味を理解できるかという問いを____という。", "____とは、中国語辞書（中中辞典）のみから中国語の意味を理解できるかという問いのことである。"],
        answer:"記号接地問題",choices:["記号接地問題","フレーム問題","チューリングテスト","中国語の部屋"],
        accept:["記号接地問題","symbol grounding problem","記号接地"],
        explanation:"記号接地問題はHarnad(1990)が提起。AIが記号の意味を真に理解しているかという根本的問い。"},
      {id:"fb041",lecture_id:"lec06",page:6,mode:"choice",
        text:"パースによる推論の三分法は____（演繹）と____（帰納・アブダクション）に大別される。", texts:["パースによる推論の三分法は____（演繹）と____（帰納・アブダクション）に大別される。", "パースによる推論の三分法は____（演繹）と____（帰納・アブダクション）に大別される。"],
        answer:"分析的推論・拡張的推論",choices:["分析的推論・拡張的推論","演繹的推論・帰納的推論","形式的推論・非形式的推論","確実的推論・不確実的推論"],
        accept:["分析的","拡張的"],
        explanation:"演繹は分析的推論（前提に含まれる情報の解明）、帰納とアブダクションは拡張的推論（前提を超えた知識拡張）。"},
      // lec08
      {id:"fb042",lecture_id:"lec08",page:4,mode:"choice",
        text:"身体を持って実世界で動くAIを____という。", texts:["身体を持って実世界で動くAIを____という。", "____とは、身体を持って実世界で動くAIのことである。"],
        answer:"フィジカルAI",choices:["フィジカルAI","エンボディドAI","ロボットAI","マルチモーダルAI"],
        accept:["フィジカルai","physical ai","フィジカルエーアイ"],
        explanation:"フィジカルAIはロボット・ヒューマノイド・自動運転車などを含む。LLMと違い触覚・力覚などのデータが少ない点が課題。"},
      {id:"fb043",lecture_id:"lec08",page:7,mode:"choice",
        text:"現実世界のデジタルコピーを仮想世界に再現し、その知見を現実にフィードバックする技術を____という。", texts:["現実世界のデジタルコピーを仮想世界に再現し、その知見を現実にフィードバックする技術を____という。", "____とは、現実世界のデジタルコピーを仮想世界に再現し、その知見を現実にフィードバックする技術のことである。"],
        answer:"デジタルツイン",choices:["デジタルツイン","Sim2Real","深層強化学習","VLAモデル"],
        accept:["デジタルツイン","digital twin"],
        explanation:"デジタルツインはフィジカルAIの課題（実世界データ取得困難）を解決するための重要技術。"},
      {id:"fb044",lecture_id:"lec08",page:9,mode:"choice",
        text:"シミュレーションで学習したポリシーや知識を実ロボットに適用する技術を____という。", texts:["シミュレーションで学習したポリシーや知識を実ロボットに適用する技術を____という。", "____とは、シミュレーションで学習したポリシーや知識を実ロボットに適用する技術のことである。"],
        answer:"Sim2Real",choices:["Sim2Real","デジタルツイン","転移学習","ドメイン適応"],
        accept:["sim2real","sim to real","sim-to-real"],
        explanation:"Sim2Realはデジタルツインと深層強化学習を組み合わせて使われる。現実では取得困難なデータを仮想環境で大量生成できる。"},
      {id:"fb045",lecture_id:"lec08",page:13,mode:"choice",
        text:"カメラ画像（V）と言語指示（L）をもとにロボットの行動（A）を出力するモデルを____という。", texts:["カメラ画像（V）と言語指示（L）をもとにロボットの行動（A）を出力するモデルを____という。", "____とは、カメラ画像（V）と言語指示（L）をもとにロボットの行動（A）を出力するモデルのことである。"],
        answer:"VLA（Vision-Language-Action）モデル",choices:["VLA（Vision-Language-Action）モデル","VLM（Vision-Language Model）","ViT（Vision Transformer）","CLIP"],
        accept:["vla","vision language action","visionlanguageaction"],
        explanation:"VLA（Vision-Language-Action）モデルはカメラ入力と言語指示からロボット行動を生成するフィジカルAIの最先端モデル。"},
      {id:"fb046",lecture_id:"lec08",page:18,mode:"choice",
        text:"ある事物の振る舞いに対して、自律的な目的・志向性に基づくと認知される心理的反応を____という。", texts:["ある事物の振る舞いに対して、自律的な目的・志向性に基づくと認知される心理的反応を____という。", "____とは、ある事物の振る舞いに対して、自律的な目的・志向性に基づくと認知される心理的反応のことである。"],
        answer:"エージェンシー認知",choices:["エージェンシー認知","志向性","他者性","AIアラインメント"],
        accept:["エージェンシー認知","agency recognition"],
        explanation:"エージェンシー認知は「心を持っているようだ」という認識を与える。未来のAIエージェント設計において重要。"},
      {id:"fb047",lecture_id:"lec08",page:22,mode:"choice",
        text:"AIと人間の価値観・目標を整合させることを____という。", texts:["AIと人間の価値観・目標を整合させることを____という。", "____とは、AIと人間の価値観・目標を整合させることのことである。"],
        answer:"AIアラインメント",choices:["AIアラインメント","AIセーフティ","AIガバナンス","AIエシックス"],
        accept:["aiアラインメント","ai alignment","アラインメント"],
        explanation:"AIアラインメントは人とAIの共生のための課題への具体的アプローチ。田中研のAFSもこれに取り組む研究の一例。"},
      {id:"fb048",lecture_id:"lec08",page:24,mode:"input",
        text:"田中研が開発中の、人とAIから構成される「家族」を最小単位の共生社会と捉えたシステム基盤を____という（英語略称も可）。", texts:["田中研が開発中の、人とAIから構成される「家族」を最小単位の共生社会と捉えたシステム基盤を____という（英語略称も可）。", "____とは、田中研が開発中の、人とAIから構成される「家族」を最小単位の共生社会と捉えたシステム基盤のことである（英語略称も可）。"],
        answer:"Agentic Family System（AFS）",accept:["afs","agentic family system","agenticfamilysystem"],
        explanation:"AFSはOlsonの円環モデル等の家族心理学理論を人-AI家族に拡張し、安全・快適な共生社会の実現を目指す。"},
      // 追加問題
      {id:"fb049",lecture_id:"lec03",page:11,mode:"choice",
        text:"テキストをトークンID列に変換（エンコード）し、逆にトークンID列をテキストに変換（デコード）するモジュールを____という。", texts:["テキストをトークンID列に変換（エンコード）し、逆にトークンID列をテキストに変換（デコード）するモジュールを____という。", "____とは、テキストをトークンID列に変換（エンコード）し、逆にトークンID列をテキストに変換（デコード）するモジュールのことである。"],
        answer:"トークナイザ",choices:["トークナイザ","エンコーダ","デコーダ","語彙表"],
        accept:["トークナイザ","tokenizer"],
        explanation:"トークナイザはLLMへの入力変換の第一段階。Transformerの学習とは別に大規模コーパスから事前学習で語彙表が作られる。"},
      {id:"fb050",lecture_id:"lec04",page:6,mode:"choice",
        text:"パーセプトロンが扱える問題のクラスは____な問題のみである。", texts:["パーセプトロンが扱える問題のクラスは____な問題のみである。", "パーセプトロンが扱える問題のクラスは____な問題のみである。"],
        answer:"線形分離可能",choices:["線形分離可能","非線形分離可能","任意の","多クラス分類"],
        accept:["線形分離","線形分離可能","linearly separable"],
        explanation:"単層パーセプトロンは線形分離不可能な問題（XOR等）を解けない。この限界が多層化への動機になった。"},
      {id:"fb051",lecture_id:"lec02",page:8,mode:"input",
        text:"AIのモデルから所望の出力を得るためのプロンプトを作成するプロセスを____という。", texts:["AIのモデルから所望の出力を得るためのプロンプトを作成するプロセスを____という。", "____とは、AIのモデルから所望の出力を得るためのプロンプトを作成するプロセスのことである。"],
        answer:"プロンプトエンジニアリング",accept:["プロンプトエンジニアリング","prompt engineering"],
        explanation:"モデルに正確な指示・例・必要な文脈情報を与えることで出力を改善できる。"},
      {id:"fb052",lecture_id:"lec05",page:14,mode:"choice",
        text:"知識や特徴量を人手を介さずデータから自動的に得る学習を____という。これが古典的AIとの最大の違いである。", texts:["知識や特徴量を人手を介さずデータから自動的に得る学習を____という。これが古典的AIとの最大の違いである。", "____とは、知識や特徴量を人手を介さずデータから自動的に得る学習のことである。これが古典的AIとの最大の違いである。"],
        answer:"表現学習",choices:["表現学習","教師あり学習","転移学習","強化学習"],
        accept:["表現学習","representation learning"],
        explanation:"古典的AIは知識を人手で記述。現代AI（深層学習）は大規模データから知識・特徴量を自動的に獲得する。"},
      {id:"fb053",lecture_id:"lec06",page:12,mode:"input",
        text:"アブダクションで観察した驚くべき事実Cを説明するために構成する仮説を____という。", texts:["アブダクションで観察した驚くべき事実Cを説明するために構成する仮説を____という。", "____とは、アブダクションで観察した驚くべき事実Cを説明するために構成する仮説のことである。"],
        answer:"説明仮説H",accept:["説明仮説h","説明仮説","仮説h","h"],
        explanation:"ニュートンの例では「万有引力の法則」が説明仮説Hに当たる。"},
      {id:"fb054",lecture_id:"lec08",page:12,mode:"choice",
        text:"物体が持つ、それを使う主体に対して提供する行動可能性を____という。", texts:["物体が持つ、それを使う主体に対して提供する行動可能性を____という。", "____とは、物体が持つ、それを使う主体に対して提供する行動可能性のことである。"],
        answer:"アフォーダンス",choices:["アフォーダンス","エージェンシー","志向性","他者性"],
        accept:["アフォーダンス","affordance"],
        explanation:"アフォーダンスはロボットが新しい機器の使い方を汎化して学習するためのポイントとして研究されている。"},
      {id:"fb055",lecture_id:"lec04",page:15,mode:"choice",
        text:"全データではなくランダムなミニバッチに対して勾配を計算してパラメータを更新する手法を____という。", texts:["全データではなくランダムなミニバッチに対して勾配を計算してパラメータを更新する手法を____という。", "____とは、全データではなくランダムなミニバッチに対して勾配を計算してパラメータを更新する手法のことである。"],
        answer:"確率的勾配降下法（SGD）",choices:["確率的勾配降下法（SGD）","勾配降下法","ニュートン法","共役勾配法"],
        accept:["sgd","確率的勾配降下法","stochastic gradient descent"],
        explanation:"確率的勾配降下法（SGD）は計算コストを削減しながら学習できる。全データを使う勾配降下法との違いはミニバッチ化。"},
      {id:"fb056",lecture_id:"lec05",page:7,mode:"choice",
        text:"機械と動物にまたがる制御と通信の統一的な理論を____という。Wienerが1943年に提唱した。", texts:["機械と動物にまたがる制御と通信の統一的な理論を____という。Wienerが1943年に提唱した。", "____とは、機械と動物にまたがる制御と通信の統一的な理論のことである。Wienerが1943年に提唱した。"],
        answer:"サイバネティクス",choices:["サイバネティクス","ダートマス理論","情報理論","制御工学"],
        accept:["サイバネティクス","cybernetics"],
        explanation:"サイバネティクスはフィードバック制御を核とし、生物から機械・社会にいたるまで考察する統一理論。"},
      {id:"fb057",lecture_id:"lec03",page:4,mode:"choice",
        text:"現代AIは概念を____で表現する（古典AIは記号で表現）。これにより「king - man + woman = queen」のような演算も可能になる。", texts:["現代AIは概念を____で表現する（古典AIは記号で表現）。これにより「king - man + woman = queen」のような演算も可能になる。", "現代AIは概念を____で表現する（古典AIは記号で表現）。これにより「king - man + woman = queen」のような演算も可能になる。"],
        answer:"高次元ベクトル",choices:["高次元ベクトル","変数","記号","論理式"],
        accept:["高次元ベクトル","ベクトル","vector"],
        explanation:"高次元ベクトル表現により類似概念間の距離関係を数値的に扱え、概念間の演算も可能になる。これが現代AIの根幹。"},
      {id:"fb058",lecture_id:"lec05",page:11,mode:"input",
        text:"スタンフォード大学で開発された代表的エキスパートシステムで、感染症診断を行うシステムを____という。", texts:["スタンフォード大学で開発された代表的エキスパートシステムで、感染症診断を行うシステムを____という。", "____とは、スタンフォード大学で開発された代表的エキスパートシステムで、感染症診断を行うシステムのことである。"],
        answer:"Mycin",accept:["mycin","マイシン"],
        explanation:"MycinはAIによる診断システムの先駆け。Dendralは有機化合物の特定を行う別のエキスパートシステム。"},
      {id:"fb059",lecture_id:"lec04",page:4,mode:"choice",
        text:"脳内のシナプスは約____個存在し、全宇宙の銀河よりも多いと言われる。", texts:["脳内のシナプスは約____個存在し、全宇宙の銀河よりも多いと言われる。", "脳内のシナプスは約____個存在し、全宇宙の銀河よりも多いと言われる。"],
        answer:"14兆",choices:["14兆","1000億","1兆","100兆"],
        accept:["14兆","14 trillion"],
        explanation:"シナプスは神経細胞同士の接続部位。約14兆個という膨大な数がヒトの脳の複雑性を支えている。"},
      {id:"fb060",lecture_id:"lec02",page:22,mode:"choice",
        text:"自己回帰言語モデルは前の出力を次の____として使いながら逐次的にトークンを予測する。", texts:["自己回帰言語モデルは前の出力を次の____として使いながら逐次的にトークンを予測する。", "自己回帰言語モデルは前の出力を次の____として使いながら逐次的にトークンを予測する。"],
        answer:"入力",choices:["入力","損失","勾配","重み"],
        accept:["入力","input"],
        explanation:"自己回帰言語モデルは「昔々ある」→「所に」→「おじいさんと」のように逐次的にトークンを予測する。"}
    ],

    essay: [
      // lec01
      {id:"es001",lecture_id:"lec01",page:9,
        question:"ハルシネーションの定義と、内因性・外因性ハルシネーションの違いを説明せよ。", texts:["ハルシネーションの定義と、内因性・外因性ハルシネーションの違いを説明せよ。", "ハルシネーションの定義と、内因性・外因性ハルシネーションの違いを簡潔に解説してください。"],
        model_answer:"ハルシネーションとは、AIが虚偽または誤解を招く情報を事実かのように提示する応答のことである。内因性ハルシネーションは学習データと異なる出力をするもの、外因性ハルシネーションは学習データに存在しないことを出力するものである。いずれも出力の事実確認（ファクトチェック）を怠ると誤った情報を正しいものとして受け取るリスクがある。",
        key_points:["ハルシネーションの定義","内因性＝学習データと異なる出力","外因性＝学習データにない内容を出力","ファクトチェックの重要性"]},
      {id:"es002",lecture_id:"lec01",page:9,
        question:"生成AI使用時の4つのリスクカテゴリを挙げ、それぞれ説明せよ。", texts:["生成AI使用時の4つのリスクカテゴリを挙げ、それぞれ説明せよ。", "生成AI使用時の4つのリスクカテゴリを挙げ、それぞれ簡潔に解説してください。"],
        model_answer:"①ハルシネーション：虚偽情報を事実かのように提示する。②権利侵害：学習データに含まれる他者の著作物・肖像権に起因して生成物の使用が侵害につながる恐れがある。③情報漏洩：入力した情報がAIの改善学習に使われる場合があり、個人情報や機密情報が漏洩するリスクがある。④その他：出力のばらつき・バイアス・ブラックボックス・倫理問題・ディープフェイクなどがある。",
        key_points:["ハルシネーション","権利侵害（著作権・肖像権）","情報漏洩","その他（ばらつき・バイアス・ブラックボックス・倫理）"]},
      // lec02
      {id:"es003",lecture_id:"lec02",page:9,
        question:"OpenAIが推奨する6つのプロンプト戦略を列挙し、特に重要なものを説明せよ。", texts:["OpenAIが推奨する6つのプロンプト戦略を列挙し、特に重要なものを説明せよ。", "OpenAIが推奨する6つのプロンプト戦略を列挙し、特に重要なものを簡潔に解説してください。"],
        model_answer:"6戦略は①明確な指示を書く、②参照テキストを提供する、③複雑なタスクを単純なサブタスクに分割する、④モデルに考える時間を与える、⑤外部ツールを使用する、⑥変更を体系的にテストする、である。特に①が重要で、詳細・背景・ペルソナ・区切り文字・ステップ明示・例・長さ指定などを含むことで出力の精度が向上する。",
        key_points:["6戦略を全て列挙","①明確な指示の内容（詳細・例・長さ等）","モデルに考える時間を与える（CoT）","外部ツール活用（RAG等）"]},
      {id:"es004",lecture_id:"lec02",page:16,
        question:"プロンプトエンジニアリングとコンテキストエンジニアリングの違いを述べよ。", texts:["プロンプトエンジニアリングとコンテキストエンジニアリングの違いを述べよ。", "プロンプトエンジニアリングとコンテキストエンジニアリングの違いをあなたの言葉で説明しなさい。"],
        model_answer:"プロンプトエンジニアリングは各回の質問の仕方（指示文）を工夫するアプローチである。コンテキストエンジニアリングはLLMの推論過程を助けうる様々な情報（コンテキスト）を与えることに注目するアプローチであり、RAG・短期/長期記憶・個人適応などが代表例である。AIが自ら推論を進める能力が高まるにつれ、コンテキストエンジニアリングへと注目が移った。",
        key_points:["プロンプトエンジニアリングの定義","コンテキストエンジニアリングの定義","RAG・記憶が代表例","移行の背景（AIの推論能力向上）"]},
      {id:"es005",lecture_id:"lec02",page:24,
        question:"LLMの事前学習とファインチューニングの2段階構造を説明せよ。", texts:["LLMの事前学習とファインチューニングの2段階構造を説明せよ。", "LLMの事前学習とファインチューニングの2段階構造を簡潔に解説してください。"],
        model_answer:"第1段階は事前学習で、大規模テキストデータ（GPT-4では約58兆トークン）を用いて基盤モデルを作る。基盤モデルはトークナイザとTransformerから構成され、続くトークンIDの確率分布を出力する。第2段階はファインチューニングで、対話・マルチモーダル等の特定タスク用データで追加学習する。ChatGPTは対話データでファインチューニングした対話型LLMである。",
        key_points:["事前学習の規模（大規模テキストデータ）","基盤モデルの構成（トークナイザ＋Transformer）","ファインチューニングの目的","ChatGPT＝対話データでFT"]},
      {id:"es006",lecture_id:"lec02",page:27,
        question:"創発的能力とは何か、なぜ衝撃的だったかを説明せよ。", texts:["創発的能力とは何か、なぜ衝撃的だったかを説明せよ。", "創発的能力とは何か、なぜ衝撃的だったかを簡潔に解説してください。"],
        model_answer:"創発的能力とは、近年のLLMが直接教えていないタスクにも対応できる汎用性の高い能力である。従来のAIは特定タスクに特化し、直接教えたタスクにしか対応できなかった。近年のLLMは大量のWebテキストデータを学習することで創発的能力を示し、汎用AIに近い性質を持つため研究者にとっても衝撃的だった。",
        key_points:["創発的能力の定義","従来AIは特化型","大量学習→汎用性の獲得","研究者への衝撃（夢のまた夢だった汎用AI）"]},
      // lec03
      {id:"es007",lecture_id:"lec03",page:4,
        question:"古典AIの記号表現と現代AIの高次元ベクトル表現の違いを説明せよ。", texts:["古典AIの記号表現と現代AIの高次元ベクトル表現の違いを説明せよ。", "古典AIの記号表現と現代AIの高次元ベクトル表現の違いを簡潔に解説してください。"],
        model_answer:"古典AIは概念を変数（記号）で表現する（例：「りんご」をAという変数で表す）。一方、現代AIは概念を高次元の数値ベクトルで表現する。高次元ベクトル表現では類似概念ほど近いベクトルになり、「king - man + woman = queen」のような概念間の演算も可能になる。この表現力の差が現代AIの汎用性の根幹となっている。",
        key_points:["古典AI＝記号（変数）","現代AI＝高次元ベクトル","類似概念は近いベクトル","概念間の演算が可能"]},
      {id:"es008",lecture_id:"lec03",page:21,
        question:"位置埋め込みが必要な理由を具体例を用いて説明せよ。", texts:["位置埋め込みが必要な理由を具体例を用いて説明せよ。", "位置埋め込みが必要な理由を具体例を用いて簡潔に解説してください。"],
        model_answer:"テキスト埋め込みだけでは「A dog bites a man.」と「A man bites a dog.」においてdogやmanが同一トークンIDを持つため、位置情報が失われる。意味が全く逆のこの2文を区別できない。そこで位置ごとに異なる値を持つ行列をテキスト埋め込み行列に加算（足し込む）ことで、各トークンに順序情報を付与する。",
        key_points:["テキスト埋め込みだけでは位置情報がない","例：dog/manの語順逆転","位置ごとに異なる行列を足し込む","これにより語順の違いを表現できる"]},
      {id:"es009",lecture_id:"lec03",page:24,
        question:"Attentionの仕組みをQ・K・V行列を用いて説明せよ。", texts:["Attentionの仕組みをQ・K・V行列を用いて説明せよ。", "Attentionの仕組みをQ・K・V行列を用いて簡潔に解説してください。"],
        model_answer:"AttentionはQ（クエリ）・K（キー）・V（バリュー）という3つの行列を用いてトークン間の関連性を実装する。QをもとにKを検索し、その類似度をもとにVを重み付きで取得する。これにより指示代名詞が何を指すか・形容詞がどの名詞にかかるかなどの関係性をベクトル演算で実現できる。距離的に遠いトークン間の関係性も扱える点が強みで、Q・K・Vの役割はデータから自動的に学習される。",
        key_points:["Q・K・Vの役割","Qで Kを検索","類似度でVを重み付け取得","距離的に遠い関係性も扱える","役割は自動学習"]},
      {id:"es010",lecture_id:"lec03",page:17,
        question:"Transformerのデコーダのみ版の全体構成を順序立てて説明せよ。", texts:["Transformerのデコーダのみ版の全体構成を順序立てて説明せよ。", "Transformerのデコーダのみ版の全体構成を順序立てて簡潔に解説してください。"],
        model_answer:"Transformerのデコーダのみ版は、①埋め込み層（テキスト埋め込み＋位置埋め込みの加算）→②マスク付きマルチヘッド注意機構（未来の情報を参照しないようマスク処理）→③フィードフォワードニューラルネットワーク、という流れを複数回繰り返す構造を持つ。最終的に続くトークンIDの確率分布を出力する。",
        key_points:["埋め込み層（テキスト埋め込み＋位置埋め込み）","マスク付きMulti-head Attention","フィードフォワードNN","複数回繰り返す","トークンIDの確率分布を出力"]},
      {id:"es011",lecture_id:"lec03",page:35,
        question:"深層学習において必要な3つの工夫（ドロップアウト・レイヤ正規化・誤差逆伝搬法）の目的をそれぞれ説明せよ。", texts:["深層学習において必要な3つの工夫（ドロップアウト・レイヤ正規化・誤差逆伝搬法）の目的をそれぞれ説明せよ。", "深層学習において必要な3つの工夫（ドロップアウト・レイヤ正規化・誤差逆伝搬法）の目的をそれぞれ簡潔に解説してください。"],
        model_answer:"①誤差逆伝搬法：順伝搬後に逆伝搬計算で勾配ベクトルを効率的に求める手法。多層NNで全パラメータの偏微分を効率的に計算するために必要。②レイヤ正規化：勾配消失や勾配爆発を防ぎ、学習効率を上げるための正規化手法。③ドロップアウト：学習時にランダムにニューロンを無効化することで過学習を防ぐ正則化手法。",
        key_points:["誤差逆伝搬法＝勾配を効率計算","レイヤ正規化＝勾配消失・爆発防止","ドロップアウト＝過学習防止","3つの組み合わせが深層学習を現実的に"]},
      // lec04
      {id:"es012",lecture_id:"lec04",page:4,
        question:"脳の神経細胞・シナプスと人工NNの対応関係を説明せよ。", texts:["脳の神経細胞・シナプスと人工NNの対応関係を説明せよ。", "脳の神経細胞・シナプスと人工NNの対応関係を簡潔に解説してください。"],
        model_answer:"脳の神経細胞（ニューロン）が人工ニューロンに、シナプス結合が重みパラメータ（w）に、活動電位の閾値が活性化関数に対応する。ただし脳にはグリア細胞（神経細胞よりも多数存在）など人工NNでは無視されている要素も多く、完全な対応ではない。人工NNは脳の数理モデルとして出発したが、現在は生物学的な正確さより工学的な性能が重視される。",
        key_points:["ニューロン→人工ニューロン","シナプス→重みパラメータ","活動電位の閾値→活性化関数","グリア細胞等の無視された要素"]},
      {id:"es013",lecture_id:"lec04",page:14,
        question:"教師あり学習の基本アルゴリズムを順序立てて説明せよ。", texts:["教師あり学習の基本アルゴリズムを順序立てて説明せよ。", "教師あり学習の基本アルゴリズムを順序立てて簡潔に解説してください。"],
        model_answer:"①パラメータを初期化する。②全学習データに対して順伝搬計算（各層の値を計算）を行い損失値を計算、損失に対する各パラメータの偏微分を計算する。③全データの偏微分から全体損失の偏微分を計算する。④勾配降下法でパラメータを修正する。これを収束するまで繰り返す。実用上は確率的勾配降下法（ミニバッチ）と誤差逆伝搬法を組み合わせる。",
        key_points:["初期化","順伝搬→損失計算","逆伝搬→勾配計算","勾配降下法でパラメータ更新","繰り返し収束まで"]},
      {id:"es014",lecture_id:"lec04",page:17,
        question:"深層学習ブームが起きた3要因を説明せよ。", texts:["深層学習ブームが起きた3要因を説明せよ。", "深層学習ブームが起きた3要因を簡潔に解説してください。"],
        model_answer:"①大規模データ：WebやSNSの普及によりビッグデータが利用可能になった。②大規模GPU：GPUの並列演算能力が深層学習の計算コストを大幅に削減した。③学習アルゴリズム：誤差逆伝搬法・ドロップアウト・レイヤ正規化などの工夫が蓄積された。2006年のHintonのオートエンコーダと2012年のAlexNetがILSVRCで圧勝したことがブームの火付け役となった。",
        key_points:["大規模データ","大規模GPU","学習アルゴリズムの工夫","AlexNet（2012）がブレイクスルー"]},
      // lec05
      {id:"es015",lecture_id:"lec05",page:4,
        question:"AIの歴史を4期に分けて概説せよ。", texts:["AIの歴史を4期に分けて概説せよ。", "AIの歴史を4期に分けて概説せよ。（分かりやすく説明すること）"],
        model_answer:"①夜明け期（1940〜50年代）：人工ニューロン（1943）・チューリング・ENIAC（1946）などの基礎概念が登場し、ダートマス会議（1956）でAIと命名された。②第1次AIブーム（1960年代）：記号処理・探索・定理証明が中心。フレーム問題が指摘された。③エキスパートシステム期（1970〜80年代）：知識表現とルールベース推論が発展し商業成功を収めたが、知識入力コスト等の限界でAIの冬の時代へ。④深層学習革命（2000年代〜）：ビッグデータ・GPU・アルゴリズムの三要素が揃いAlexNet（2012）でブレイクスルー。",
        key_points:["夜明け期・ダートマス会議","第1次ブーム・フレーム問題","エキスパートシステムとAIの冬","深層学習革命の3要因"]},
      {id:"es016",lecture_id:"lec05",page:10,
        question:"フレーム問題とは何か、なぜ古典的AIにとって問題なのか説明せよ。", texts:["フレーム問題とは何か、なぜ古典的AIにとって問題なのか説明せよ。", "フレーム問題とは何か、なぜ古典的AIにとって問題なのか簡潔に解説してください。"],
        model_answer:"フレーム問題とは、行動後に変化しなかった事柄をすべて記述・管理することの困難さである（McCarthyとHayes, 1969）。古典的AIでは知識を記号として記述するため、行動が世界に与える影響の全てを形式的に記述する必要がある。しかし現実世界では変化しない事柄の方が圧倒的に多く、それらを全て列挙することは現実的に不可能であり、古典的AIの根本的限界を示している。",
        key_points:["定義：行動後の不変事柄の記述困難","McCarthyとHayes(1969)","記号表現の限界","現実的に全列挙は不可能"]},
      {id:"es017",lecture_id:"lec05",page:20,
        question:"フレーム表現のクラスフレーム・インスタンスフレーム・デフォルト値・性質の継承を具体例を用いて説明せよ。", texts:["フレーム表現のクラスフレーム・インスタンスフレーム・デフォルト値・性質の継承を具体例を用いて説明せよ。", "フレーム表現のクラスフレーム・インスタンスフレーム・デフォルト値・性質の継承を具体例を用いて簡潔に解説してください。"],
        model_answer:"フレーム表現は、「人」や「自転車」のような抽象的概念を記述するクラスフレームと、「太郎」や「太郎の自転車」のような個別事例を記述するインスタンスフレームから構成される。デフォルト値は確定値は不明だが推定値はわかる場合に仮に与える値（例：人の身長はdefault 170cm）。性質の継承は上位概念の性質を下位概念が受け継ぐ仕組みで（例：人→太郎）、オブジェクト指向の礎となった。",
        key_points:["クラスフレーム（抽象概念）","インスタンスフレーム（個別事例）","デフォルト値の具体例","性質の継承とオブジェクト指向の関係"]},
      {id:"es018",lecture_id:"lec05",page:13,
        question:"古典的AIと現代AI（深層学習）の知識獲得方法の本質的違いを説明せよ。", texts:["古典的AIと現代AI（深層学習）の知識獲得方法の本質的違いを説明せよ。", "古典的AIと現代AI（深層学習）の知識獲得方法の本質的違いを簡潔に解説してください。"],
        model_answer:"古典的AIでは知識を人手で記号として記述し論理推論を行う。特徴量の記述にも人手を要した。これにより知識入力のコストが膨大になり、暗黙知の表現も困難だった。現代AI（深層学習）は大規模データから知識・特徴量を自動的に（表現学習で）獲得する。人手のボトルネックが解消され汎用性能が格段に向上した。",
        key_points:["古典AI＝人手による記号記述","現代AI＝データからの自動獲得（表現学習）","古典AIの限界：知識入力コスト・暗黙知","表現学習により汎用性が向上"]},
      // lec06
      {id:"es019",lecture_id:"lec06",page:6,
        question:"演繹・帰納・アブダクションをそれぞれ定義し、具体例を挙げて比較せよ。", texts:["演繹・帰納・アブダクションをそれぞれ定義し、具体例を挙げて比較せよ。", "演繹・帰納・アブダクションをそれぞれ定義し、具体例を挙げて比較せよ。（分かりやすく説明すること）"],
        model_answer:"演繹は前提とその結論との間に必然性がある分析的推論で、「すべての人は死ぬ・ソクラテスは人である・ゆえにソクラテスは死ぬ」が例。帰納は個々の事例から一般的規則を導く拡張的推論で、「犬1・犬2・犬3が吠える→すべての犬は吠える」が例。アブダクションは驚くべき事実Cを観察し、説明仮説Hを構成する拡張的推論で、「林檎が落下する（C）→万有引力の法則（H）」が例。帰納と比べアブダクションは仮説の発見という創造的側面を持つ。",
        key_points:["演繹の定義と例（三段論法）","帰納の定義と例（事例→一般化）","アブダクションの定義と例（仮説発見）","帰納vsアブダクション（一般化vs仮説発見）"]},
      {id:"es020",lecture_id:"lec06",page:14,
        question:"ニュートンの万有引力発見をアブダクションの枠組みで説明せよ。", texts:["ニュートンの万有引力発見をアブダクションの枠組みで説明せよ。", "ニュートンの万有引力発見をアブダクションの枠組みで簡潔に解説してください。"],
        model_answer:"アブダクションの枠組みでは、まず驚くべき事実C（「林檎が垂直に落下する」）を観察する。次に「もしHが真であればCは当然の事柄であろう」という説明仮説Hを構成する。ニュートンはこの驚くべき事実を素通りせず、「物質の中には引力がある→大きさの間に比例関係がある→万有引力の法則（H）」という仮説を思索し続けた。ニュートンの非凡さは驚くべき事実を驚くべき事実として捉え、説明仮説を探し続けた点にある。",
        key_points:["驚くべき事実C＝林檎の落下","説明仮説H＝万有引力の法則","アブダクションの一般形式との対応","ニュートンの非凡さの説明"]},
      {id:"es021",lecture_id:"lec06",page:18,
        question:"生成AIはアブダクションができるか。今井むつみの見解を踏まえて論じよ。", texts:["生成AIはアブダクションができるか。今井むつみの見解を踏まえて論じよ。", "生成AIはアブダクションができるか。今井むつみの見解を踏まえて論じよ。（分かりやすく説明すること）"],
        model_answer:"認知科学者・今井むつみによれば「AIは統計パターンがすべてで本質的にはアブダクションをしない」とされる。生成AIは大量のテキストパターンから確率的に次のトークンを予測するが、驚くべき事実から説明仮説を発見するという創造的プロセスを行えているかは疑わしい。一方でChatGPTにアブダクション的な推理ゲームを試みた研究もある。生成AIが真にアブダクションを行えるかは現在も未解決の問題である。",
        key_points:["今井むつみの見解（統計パターンのみ）","生成AIの仕組み（確率的トークン予測）","アブダクション＝仮説発見の創造的プロセス","未解決問題として認識する"]},
      {id:"es022",lecture_id:"lec06",page:19,
        question:"記号接地問題を説明し、AIとの関連で考察せよ。", texts:["記号接地問題を説明し、AIとの関連で考察せよ。", "記号接地問題を説明し、AIとの関連で考察せよ。（分かりやすく説明すること）"],
        model_answer:"記号接地問題とは、中国語辞書（中中辞典）のみから中国語の意味を理解できるかという問いである（Harnad, 1990）。記号から記号へと回り続けるだけで、現実の概念に「接地」できない状態を指す。AIがテキスト（記号）から記号へと処理を行うだけでは、その記号が現実世界の概念に接地しているかが疑わしい。フィジカルAIのように実世界センサを通じた接地が今後の課題とされる。",
        key_points:["定義：記号から記号へのループ","Harnad(1990)","AIへの適用（テキスト処理の限界）","フィジカルAIによる接地の可能性"]},
      // lec08
      {id:"es023",lecture_id:"lec08",page:6,
        question:"フィジカルAIとLLM（テキストAI）の違いと課題を説明せよ。", texts:["フィジカルAIとLLM（テキストAI）の違いと課題を説明せよ。", "フィジカルAIとLLM（テキストAI）の違いと課題を簡潔に解説してください。"],
        model_answer:"LLMは主にインターネット上のテキスト・画像データで作られ、言語や抽象的概念を扱える。一方フィジカルAIは身体を持って実世界で動くAIであり、ロボット・自動運転車などが含まれる。LLMとの違いは、触覚・力覚などの実世界センサ入力も必要で、空間的関係性や物理法則を理解した上での行動生成が求められる点である。実世界データの取得・学習・活用が主要課題である。",
        key_points:["LLM＝テキスト・画像データ","フィジカルAI＝実世界で動く","触覚・力覚等の実世界センサ","実世界データ取得・学習・活用が課題"]},
      {id:"es024",lecture_id:"lec08",page:8,
        question:"デジタルツインとSim2Realを組み合わせたアプローチを説明せよ。", texts:["デジタルツインとSim2Realを組み合わせたアプローチを説明せよ。", "デジタルツインとSim2Realを組み合わせたアプローチを簡潔に解説してください。"],
        model_answer:"現実世界でのデータ取得は危険・困難なことが多い（人に飛びつくロボット等）。そこでデジタルツインで現実世界の仮想コピーを作成し、仮想環境上で深層強化学習シミュレーションを行い、最適な制御ポリシーを学習する。その後Sim2Realで学習したポリシーを実ロボットに転移する。現実では取得困難なデータを仮想環境で大量生成できる点が強みである。",
        key_points:["現実データ取得の困難さ","デジタルツインで仮想環境を構築","仮想環境で深層強化学習","Sim2Realで実ロボットへ転移"]},
      {id:"es025",lecture_id:"lec08",page:18,
        question:"エージェンシー認知とは何か、AIエージェント設計との関連で説明せよ。", texts:["エージェンシー認知とは何か、AIエージェント設計との関連で説明せよ。", "エージェンシー認知とは何か、AIエージェント設計との関連で簡潔に解説してください。"],
        model_answer:"エージェンシー認知とは、環境内のある事物の振る舞いに対して、自律的な目的あるいは志向性に基づくものであると認知される心理的反応である。「心を持っているようだ」「意図があるかのようだ」という認識を与える。従来のAIエージェント論はサービス・機能提供に注目してきたが、エージェンシー認知の観点から「他者性」が価値を持つという視点が重要である。田中によれば、望ましい他者性の設計論を備えたものが未来のAIエージェントとなる。",
        key_points:["エージェンシー認知の定義","志向性との関係","他者性が価値を持つという視点","未来のAIエージェント設計への示唆"]},
      {id:"es026",lecture_id:"lec08",page:22,
        question:"AIアラインメントとAgentic Family Systemのコンセプトを説明せよ。", texts:["AIアラインメントとAgentic Family Systemのコンセプトを説明せよ。", "AIアラインメントとAgentic Family Systemのコンセプトを簡潔に解説してください。"],
        model_answer:"AIアラインメントはAIと人間の価値観・目標を整合させることであり、人とAIの共生における核心課題である。田中研のAgentic Family System（AFS）は「家族」という最小単位から人-AI共生社会を構築するアプローチで、Olsonの円環モデル等の家族心理学理論を人-AI家族に拡張する。独り暮らしの安全基地提供・世帯家族の良好なコミュニケーション維持が具体的な応用先として挙げられている。",
        key_points:["AIアラインメントの定義","AFSのコンセプト（家族が最小単位）","家族心理学理論（Olsonの円環モデル）","具体的応用先（独居サポート等)"]}
    ]
  }
};
